### ISSUE TITLE
"Now Playing" window only displays a Skull after the rotating hammer

### ISSUE THREAD

**Issue by mbrpistoni** [casparluc/VikingDoom#3] opened 2017-03-13 10:27 UTC
Hi!
When I open your website, I can't see any game running. First I see a rotating hammer, then a Skull. This problem happens in Firefox and Google Chrome (both updated to most recent version). I contact you through email and I was suggested that maybe the browser is not supporting websockets. I did a test and it does (chrome supports it since v4 by default). I tried again from my work computer, same result. 
I'm attaching 2 pictures of the test I run and the "error" I got.
Let me know if I can run any other test for you guys. 
 
![error2](https://cloud.githubusercontent.com/assets/5014811/23850478/91d2c3a6-07d7-11e7-89bf-90f4e3d7b6d7.png)
![error1](https://cloud.githubusercontent.com/assets/5014811/23850479/91d3979a-07d7-11e7-8176-61ccb1b8c909.png)

**Comment by davinellulinvega** [comment] 2017-03-13 12:51
Hello,

The fact that at first you can see the rotating hammer and then get the skull makes all the difference in the world. This means that the websocket connection is correctly established for some time, but suddenly dropped by the server.
Since you went to great length and even tried to access the website from your computer at work, it would seem that the problem is not with the javascript or your setup, but with the server itself.
To ensure that all personal data on the server was _safe_, I had to reinforce the server's security quite a bit and in the process I forgot to leave a port open, in the firewall, for the websocket server. This mistake has been dealt with. You should now be able to see the hammer for a longer period of time and even games if someone is currently playing.

I am really sorry for the inconvenience. If you could please confirm that it is indeed working well for you now, before closing the issue.

Sincerely.

**Comment by mbrpistoni** [comment] 2017-03-13 14:37
Hi!
Ok, no skull now, just the rotating hammer, spinning forever. 
I don't know if that's the correct behavior or I should see some kind of gameplay (maybe nobody is playing now?). 
It would help if you add an screenshot of how the game looks like when running in the docs. Also some text while the hammer spins like "looking for players" or something like that.

**Comment by davinellulinvega** [comment] 2017-03-13 14:47
Hello,

It is indeed my intention to include some screen shots on the "docs" page, so that people can have a look at the game.

Sincerely.

**Closed as completed by davinellulinvega** 2017-03-13 14:47 UTC

**Comment by mbrpistoni** [comment] 2017-03-13 14:59
ok, after few minutes, I can see the game. All good now!
Here is an screenshot, in case you want it.
Thanks for the help!

![untitled](https://cloud.githubusercontent.com/assets/5014811/23860048/a6a7e236-07fd-11e7-9484-d16297b3524d.png)
